spring:
  # Import Base Configuration
  config:
    import: classpath:/base-config-application.yaml
  # Enable Virtual Threads
  threads:
    virtual:
      enabled: true
base:
  errorhandler:
    enabled: false
  feign:
    extension:
      enabled: false
  logging:
    request:
      enabled: true
  meter:
    aspect:
      enabled: true

# Actuator Configuration
management:
  observations:
    key-values:
      application: @project.name@

# Information for the /info Endpoint#
info:
  app:
    name: @project.name@
    version: @project.version@

# diesease configuration
disease:
  config: classpath:diseaseConfiguration.json
  config-show-all-scenario-passed: true
  fhir-path-data: configuration/diseaseScenarios.json

feature:
  flag:
    accepting_anonymous_notifications: false
    notifications.7_3: false
